export type NavSite = {
  id: string;
  name: string;
  url: string;
  desc: string;
  category: string;
  tags: string[];
  mark?: string;
  badge?: string;
  isCustom?: boolean;
};

export const categories = [
  { id: "all", name: "全部网站", icon: "⌂", eyebrow: "ALL DESTINATIONS" },
  { id: "featured", name: "今日推荐", icon: "✦", eyebrow: "CURATED FOR YOU" },
  { id: "movie", name: "影视", icon: "▷", eyebrow: "MOVIES & TV" },
  { id: "anime", name: "动漫", icon: "◌", eyebrow: "ANIME WORLD" },
  { id: "reading", name: "阅读", icon: "▤", eyebrow: "READING ROOM" },
  { id: "music", name: "音乐", icon: "♫", eyebrow: "LISTEN NOW" },
  { id: "game", name: "游戏", icon: "♧", eyebrow: "GAME ON" },
  { id: "tools", name: "实用工具", icon: "⌘", eyebrow: "USEFUL TOOLS" },
  { id: "design", name: "设计灵感", icon: "◇", eyebrow: "DESIGN PICKS" },
  { id: "dev", name: "开发者", icon: "⌗", eyebrow: "FOR DEVELOPERS" },
] as const;

export const defaultSites: NavSite[] = [
  {
    id: "bilibili",
    name: "哔哩哔哩",
    url: "https://www.bilibili.com/",
    desc: "年轻人的文化社区与视频平台",
    category: "featured",
    tags: ["视频", "社区"],
    mark: "B",
    badge: "热门",
  },
  {
    id: "douban",
    name: "豆瓣",
    url: "https://www.douban.com/",
    desc: "电影、读书与生活方式社区",
    category: "featured",
    tags: ["评分", "发现"],
    mark: "豆",
  },
  {
    id: "zhihu",
    name: "知乎",
    url: "https://www.zhihu.com/",
    desc: "可信赖的问答与知识社区",
    category: "featured",
    tags: ["知识", "社区"],
    mark: "知",
  },
  {
    id: "weread",
    name: "微信读书",
    url: "https://weread.qq.com/",
    desc: "随时随地阅读优质电子书",
    category: "featured",
    tags: ["阅读", "书评"],
    mark: "读",
  },
  {
    id: "cloudmusic",
    name: "网易云音乐",
    url: "https://music.163.com/",
    desc: "发现好音乐与宝藏歌单",
    category: "featured",
    tags: ["音乐", "歌单"],
    mark: "音",
  },
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com/",
    desc: "全球开发者的代码与协作平台",
    category: "featured",
    tags: ["开源", "开发"],
    mark: "G",
    badge: "推荐",
  },
  {
    id: "qiyi",
    name: "爱奇艺",
    url: "https://www.iqiyi.com/",
    desc: "电影、剧集与综艺内容平台",
    category: "movie",
    tags: ["剧集", "综艺"],
    mark: "奇",
  },
  {
    id: "tencent-video",
    name: "腾讯视频",
    url: "https://v.qq.com/",
    desc: "热播剧集、电影与体育赛事",
    category: "movie",
    tags: ["影视", "体育"],
    mark: "腾",
  },
  {
    id: "youku",
    name: "优酷",
    url: "https://www.youku.com/",
    desc: "精品剧集、综艺与纪录片",
    category: "movie",
    tags: ["剧集", "纪录片"],
    mark: "优",
  },
  {
    id: "mgtv",
    name: "芒果TV",
    url: "https://www.mgtv.com/",
    desc: "湖南卫视旗下在线视频平台",
    category: "movie",
    tags: ["综艺", "剧集"],
    mark: "芒",
  },
  {
    id: "mtime",
    name: "时光网",
    url: "https://www.mtime.com/",
    desc: "电影资讯、影讯与专业资料",
    category: "movie",
    tags: ["影讯", "资料"],
    mark: "时",
  },
  {
    id: "netflix",
    name: "Netflix",
    url: "https://www.netflix.com/",
    desc: "全球流媒体电影与剧集平台",
    category: "movie",
    tags: ["流媒体", "海外"],
    mark: "N",
  },
  {
    id: "bangumi",
    name: "Bangumi",
    url: "https://bangumi.tv/",
    desc: "专注动漫、书籍与游戏的资料库",
    category: "anime",
    tags: ["番组", "评分"],
    mark: "番",
  },
  {
    id: "bilibili-anime",
    name: "B站番剧",
    url: "https://www.bilibili.com/anime/",
    desc: "正版新番、国创与经典动画",
    category: "anime",
    tags: ["番剧", "国创"],
    mark: "B",
  },
  {
    id: "acfun",
    name: "AcFun",
    url: "https://www.acfun.cn/",
    desc: "弹幕视频与二次元内容社区",
    category: "anime",
    tags: ["弹幕", "二次元"],
    mark: "A",
  },
  {
    id: "anilist",
    name: "AniList",
    url: "https://anilist.co/",
    desc: "追踪动画进度与发现新作品",
    category: "anime",
    tags: ["追番", "资料"],
    mark: "A",
  },
  {
    id: "myanimelist",
    name: "MyAnimeList",
    url: "https://myanimelist.net/",
    desc: "全球动漫资料与评分社区",
    category: "anime",
    tags: ["动漫", "评分"],
    mark: "M",
  },
  {
    id: "dmzj",
    name: "动漫之家",
    url: "https://www.dmzj.com/",
    desc: "漫画、轻小说与动漫资讯",
    category: "anime",
    tags: ["漫画", "轻小说"],
    mark: "漫",
  },
  {
    id: "qidian",
    name: "起点中文网",
    url: "https://www.qidian.com/",
    desc: "原创文学与网络小说阅读平台",
    category: "reading",
    tags: ["小说", "原创"],
    mark: "起",
  },
  {
    id: "jjwxc",
    name: "晋江文学城",
    url: "https://www.jjwxc.net/",
    desc: "原创网络文学阅读与创作平台",
    category: "reading",
    tags: ["文学", "原创"],
    mark: "晋",
  },
  {
    id: "fanqie",
    name: "番茄小说",
    url: "https://fanqienovel.com/",
    desc: "轻松发现海量小说内容",
    category: "reading",
    tags: ["小说", "阅读"],
    mark: "番",
  },
  {
    id: "douban-read",
    name: "豆瓣阅读",
    url: "https://read.douban.com/",
    desc: "高品质原创作品与电子书",
    category: "reading",
    tags: ["电子书", "原创"],
    mark: "豆",
  },
  {
    id: "gutenberg",
    name: "Project Gutenberg",
    url: "https://www.gutenberg.org/",
    desc: "超过七万本免费公共版权电子书",
    category: "reading",
    tags: ["英文", "免费"],
    mark: "G",
  },
  {
    id: "goodreads",
    name: "Goodreads",
    url: "https://www.goodreads.com/",
    desc: "全球读者的书籍与阅读社区",
    category: "reading",
    tags: ["书单", "评分"],
    mark: "G",
  },
  {
    id: "qqmusic",
    name: "QQ音乐",
    url: "https://y.qq.com/",
    desc: "海量正版音乐与个性化推荐",
    category: "music",
    tags: ["音乐", "MV"],
    mark: "Q",
  },
  {
    id: "spotify",
    name: "Spotify",
    url: "https://open.spotify.com/",
    desc: "全球音乐、播客与个性歌单",
    category: "music",
    tags: ["歌单", "播客"],
    mark: "S",
  },
  {
    id: "applemusic",
    name: "Apple Music",
    url: "https://music.apple.com/",
    desc: "高品质音乐与空间音频体验",
    category: "music",
    tags: ["无损", "电台"],
    mark: "A",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    url: "https://soundcloud.com/",
    desc: "发现独立音乐人与新鲜声音",
    category: "music",
    tags: ["独立音乐", "创作"],
    mark: "S",
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    url: "https://bandcamp.com/",
    desc: "直接支持音乐人与独立唱片",
    category: "music",
    tags: ["独立", "唱片"],
    mark: "B",
  },
  {
    id: "steam",
    name: "Steam",
    url: "https://store.steampowered.com/",
    desc: "PC 游戏商店与玩家社区",
    category: "game",
    tags: ["PC", "社区"],
    mark: "S",
  },
  {
    id: "epic",
    name: "Epic Games",
    url: "https://store.epicgames.com/",
    desc: "PC 游戏商城与每周免费游戏",
    category: "game",
    tags: ["PC", "商城"],
    mark: "E",
  },
  {
    id: "taptap",
    name: "TapTap",
    url: "https://www.taptap.cn/",
    desc: "好游戏发现与玩家交流社区",
    category: "game",
    tags: ["手游", "评测"],
    mark: "T",
  },
  {
    id: "nga",
    name: "NGA",
    url: "https://bbs.nga.cn/",
    desc: "专业玩家社区与游戏讨论",
    category: "game",
    tags: ["论坛", "攻略"],
    mark: "N",
  },
  {
    id: "ign",
    name: "IGN",
    url: "https://www.ign.com/",
    desc: "全球游戏资讯、攻略与评测",
    category: "game",
    tags: ["资讯", "评测"],
    mark: "I",
  },
  {
    id: "speedtest",
    name: "Speedtest",
    url: "https://www.speedtest.net/",
    desc: "快速测试网络速度与延迟",
    category: "tools",
    tags: ["测速", "网络"],
    mark: "S",
  },
  {
    id: "translate",
    name: "Google 翻译",
    url: "https://translate.google.com/",
    desc: "覆盖多语言的在线翻译工具",
    category: "tools",
    tags: ["翻译", "语言"],
    mark: "译",
  },
  {
    id: "tinypng",
    name: "TinyPNG",
    url: "https://tinypng.com/",
    desc: "智能压缩 PNG、WebP 与 JPEG",
    category: "tools",
    tags: ["图片", "压缩"],
    mark: "T",
  },
  {
    id: "convertio",
    name: "Convertio",
    url: "https://convertio.co/zh/",
    desc: "支持三百多种格式的在线转换器",
    category: "tools",
    tags: ["转换", "文件"],
    mark: "C",
  },
  {
    id: "removebg",
    name: "remove.bg",
    url: "https://www.remove.bg/zh",
    desc: "一键移除图片背景",
    category: "tools",
    tags: ["抠图", "图片"],
    mark: "R",
  },
  {
    id: "excalidraw",
    name: "Excalidraw",
    url: "https://excalidraw.com/",
    desc: "手绘风格的在线白板工具",
    category: "tools",
    tags: ["白板", "绘图"],
    mark: "E",
  },
  {
    id: "figma",
    name: "Figma",
    url: "https://www.figma.com/",
    desc: "协作式界面设计与原型工具",
    category: "design",
    tags: ["UI", "协作"],
    mark: "F",
  },
  {
    id: "behance",
    name: "Behance",
    url: "https://www.behance.net/",
    desc: "全球创意作品展示与灵感社区",
    category: "design",
    tags: ["作品集", "灵感"],
    mark: "B",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    url: "https://dribbble.com/",
    desc: "设计师作品、趋势与灵感平台",
    category: "design",
    tags: ["UI", "灵感"],
    mark: "D",
  },
  {
    id: "awwwards",
    name: "Awwwards",
    url: "https://www.awwwards.com/",
    desc: "全球优秀网站设计奖项与案例",
    category: "design",
    tags: ["网页", "案例"],
    mark: "W",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    url: "https://unsplash.com/",
    desc: "高质量可商用摄影图库",
    category: "design",
    tags: ["摄影", "图库"],
    mark: "U",
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    url: "https://stackoverflow.com/",
    desc: "开发者问答与技术知识库",
    category: "dev",
    tags: ["问答", "编程"],
    mark: "S",
  },
  {
    id: "mdn",
    name: "MDN Web Docs",
    url: "https://developer.mozilla.org/zh-CN/",
    desc: "可靠的 Web 技术文档与指南",
    category: "dev",
    tags: ["文档", "Web"],
    mark: "M",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://vercel.com/",
    desc: "现代 Web 应用部署与托管平台",
    category: "dev",
    tags: ["部署", "前端"],
    mark: "V",
  },
  {
    id: "npm",
    name: "npm",
    url: "https://www.npmjs.com/",
    desc: "JavaScript 包与开源生态平台",
    category: "dev",
    tags: ["前端", "包管理"],
    mark: "n",
  },
  {
    id: "can-i-use",
    name: "Can I use",
    url: "https://caniuse.com/",
    desc: "查询 Web 特性的浏览器兼容性",
    category: "dev",
    tags: ["兼容性", "Web"],
    mark: "C",
  },
];
