export type NavSite = {
  id: string;
  name: string;
  url: string;
  desc: string;
  category: string;
  tags: string[];
  mark?: string;
  badge?: string;
  isCustom?: boolean;
};

export const categories = [
  { id: "all", name: "全部网站", icon: "⌂", eyebrow: "ALL DESTINATIONS" },
  { id: "featured", name: "今日推荐", icon: "✦", eyebrow: "CURATED FOR YOU" },
  { id: "reading", name: "阅读", icon: "▤", eyebrow: "READING ROOM" },
  { id: "tools", name: "实用工具", icon: "⌘", eyebrow: "USEFUL TOOLS" },
  { id: "design", name: "设计灵感", icon: "◇", eyebrow: "DESIGN PICKS" },
  { id: "dev", name: "开发者", icon: "⌗", eyebrow: "FOR DEVELOPERS" },
] as const;

export const defaultSites: NavSite[] = [
  {
    id: "knowledge-base",
    name: "知识库",
    url: "https://docs.sgao.cc/",
    desc: "系统化沉淀与持续维护的知识专题",
    category: "featured",
    tags: ["知识", "文档"],
    mark: "知",
  },
  {
    id: "image-management",
    name: "图片管理",
    url: "https://img.sgao.cc/admin/",
    desc: "管理图片资源与图片中心内容",
    category: "featured",
    tags: ["图片", "管理"],
    mark: "图",
  },
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com/",
    desc: "全球开发者的代码与协作平台",
    category: "featured",
    tags: ["开源", "开发"],
    mark: "G",
    badge: "推荐",
  },
  {
    id: "bilibili",
    name: "哔哩哔哩",
    url: "https://www.bilibili.com/",
    desc: "年轻人的文化社区与视频平台",
    category: "featured",
    tags: ["视频", "社区"],
    mark: "B",
    badge: "热门",
  },
  {
    id: "zhihu",
    name: "知乎",
    url: "https://www.zhihu.com/",
    desc: "可信赖的问答与知识社区",
    category: "featured",
    tags: ["知识", "社区"],
    mark: "知",
  },
  {
    id: "qidian",
    name: "起点中文网",
    url: "https://www.qidian.com/",
    desc: "原创文学与网络小说阅读平台",
    category: "reading",
    tags: ["小说", "原创"],
    mark: "起",
  },
  {
    id: "jjwxc",
    name: "晋江文学城",
    url: "https://www.jjwxc.net/",
    desc: "原创网络文学阅读与创作平台",
    category: "reading",
    tags: ["文学", "原创"],
    mark: "晋",
  },
  {
    id: "fanqie",
    name: "番茄小说",
    url: "https://fanqienovel.com/",
    desc: "轻松发现海量小说内容",
    category: "reading",
    tags: ["小说", "阅读"],
    mark: "番",
  },
  {
    id: "douban-read",
    name: "豆瓣阅读",
    url: "https://read.douban.com/",
    desc: "高品质原创作品与电子书",
    category: "reading",
    tags: ["电子书", "原创"],
    mark: "豆",
  },
  {
    id: "gutenberg",
    name: "Project Gutenberg",
    url: "https://www.gutenberg.org/",
    desc: "超过七万本免费公共版权电子书",
    category: "reading",
    tags: ["英文", "免费"],
    mark: "G",
  },
  {
    id: "goodreads",
    name: "Goodreads",
    url: "https://www.goodreads.com/",
    desc: "全球读者的书籍与阅读社区",
    category: "reading",
    tags: ["书单", "评分"],
    mark: "G",
  },
  {
    id: "speedtest",
    name: "Speedtest",
    url: "https://www.speedtest.net/",
    desc: "快速测试网络速度与延迟",
    category: "tools",
    tags: ["测速", "网络"],
    mark: "S",
  },
  {
    id: "translate",
    name: "Google 翻译",
    url: "https://translate.google.com/",
    desc: "覆盖多语言的在线翻译工具",
    category: "tools",
    tags: ["翻译", "语言"],
    mark: "译",
  },
  {
    id: "tinypng",
    name: "TinyPNG",
    url: "https://tinypng.com/",
    desc: "智能压缩 PNG、WebP 与 JPEG",
    category: "tools",
    tags: ["图片", "压缩"],
    mark: "T",
  },
  {
    id: "convertio",
    name: "Convertio",
    url: "https://convertio.co/zh/",
    desc: "支持三百多种格式的在线转换器",
    category: "tools",
    tags: ["转换", "文件"],
    mark: "C",
  },
  {
    id: "removebg",
    name: "remove.bg",
    url: "https://www.remove.bg/zh",
    desc: "一键移除图片背景",
    category: "tools",
    tags: ["抠图", "图片"],
    mark: "R",
  },
  {
    id: "excalidraw",
    name: "Excalidraw",
    url: "https://excalidraw.com/",
    desc: "手绘风格的在线白板工具",
    category: "tools",
    tags: ["白板", "绘图"],
    mark: "E",
  },
  {
    id: "figma",
    name: "Figma",
    url: "https://www.figma.com/",
    desc: "协作式界面设计与原型工具",
    category: "design",
    tags: ["UI", "协作"],
    mark: "F",
  },
  {
    id: "behance",
    name: "Behance",
    url: "https://www.behance.net/",
    desc: "全球创意作品展示与灵感社区",
    category: "design",
    tags: ["作品集", "灵感"],
    mark: "B",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    url: "https://dribbble.com/",
    desc: "设计师作品、趋势与灵感平台",
    category: "design",
    tags: ["UI", "灵感"],
    mark: "D",
  },
  {
    id: "awwwards",
    name: "Awwwards",
    url: "https://www.awwwards.com/",
    desc: "全球优秀网站设计奖项与案例",
    category: "design",
    tags: ["网页", "案例"],
    mark: "W",
  },
  {
    id: "unsplash",
    name: "Unsplash",
    url: "https://unsplash.com/",
    desc: "高质量可商用摄影图库",
    category: "design",
    tags: ["摄影", "图库"],
    mark: "U",
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    url: "https://stackoverflow.com/",
    desc: "开发者问答与技术知识库",
    category: "dev",
    tags: ["问答", "编程"],
    mark: "S",
  },
  {
    id: "mdn",
    name: "MDN Web Docs",
    url: "https://developer.mozilla.org/zh-CN/",
    desc: "可靠的 Web 技术文档与指南",
    category: "dev",
    tags: ["文档", "Web"],
    mark: "M",
  },
  {
    id: "vercel",
    name: "Vercel",
    url: "https://vercel.com/",
    desc: "现代 Web 应用部署与托管平台",
    category: "dev",
    tags: ["部署", "前端"],
    mark: "V",
  },
  {
    id: "npm",
    name: "npm",
    url: "https://www.npmjs.com/",
    desc: "JavaScript 包与开源生态平台",
    category: "dev",
    tags: ["前端", "包管理"],
    mark: "n",
  },
  {
    id: "can-i-use",
    name: "Can I use",
    url: "https://caniuse.com/",
    desc: "查询 Web 特性的浏览器兼容性",
    category: "dev",
    tags: ["兼容性", "Web"],
    mark: "C",
  },
];
